version: '2'

services:
  web:
    image: lazyfrosch/icingaweb2
    #build: .
    environment:
      ICINGAWEB_TIMEZONE: 'Europe/Berlin'
    ports:
      - 8080:80
    volumes:
      - config:/etc/icingaweb2
    depends_on:
      - db
  db:
    image: mariadb
    volumes:
      - database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: onlyforadmin
      MYSQL_DATABASE: icingaweb2
      MYSQL_USER: icingaweb2
      MYSQL_PASSWORD: rosebud

volumes:
  config:
  database:
