---
web:
  image: lazyfrosch/icingaweb2
  #build: .
  ports:
    - 8080:80
  links:
    - db
db:
  image: mariadb
  environment:
    MYSQL_ROOT_PASSWORD: onlyforadmin
    MYSQL_DATABASE: icingaweb2
    MYSQL_USER: icingaweb2
    MYSQL_PASSWORD: rosebud
